---
# Arquivo de configuração principal para o plugin [Título] do software para PocketMine-MP
# Criado oficialmente por @LewBr, http://twitter.com/lew_br/

#Abreviações básicas do plugin para obter uma função ou algo relacionado ao plugin:
#1. {jogador} - retorna o nome do jogador que entrou no servidor relacionado;
#2. & - utilizado muitas vezes em alguns dos meus plugins, seria uma "tradução" do §, assim poderia não haver erros na salvação do arquivo relacionados a caracteres especiais UTF. 

configuracoes:
 simbolo_cor: "&"

 #Alteração do texto principal (maior)
 #Exemplo:
 #titulo_principal: "&6Seja bem-vindo {jogador}"
 titulo_principal: "texto_1"

 #Alteração do texto abaixo (menor)
 #Exemplo:
 #titulo_abaixo: "&7{jogador} você é especial para todos nós! :)"
 titulo_abaixo: "texto_2"

 #Tempo em que a mensagem ficará na tela do jogador, calculado por segundos (padrão: 5 segundos)
 tempo: 5
...